AWSTemplateFormatVersion: 2010-09-09

Description: A4A Auto-scaling group configuration

Parameters:
  EnvironmentName:
    Description: Identify environment as non-prod or production
    Type: String
    Default: non-prod
    AllowedValues:
        - 'non-prod'
        - 'prod'
    ConstraintDescription: Specify either non-prod or prod
  ApplicationName:
    Description: The name of the application
    Type: String
  Role:
    Description: name of the tier
    Type: String
    Default: web
  AmiId:
    Description: The AMI ID
    Type: AWS::EC2::Image::Id
  MaximumInstances:
    Description: The maximum number of instances
    Type: Number
    Default: 2
  MinimumInstances:
    Description: The minimum number of instances
    Type: Number
    Default: 1
  MinimumViableInstances:
    Description: The number of instances
    Type: Number
    Default: 1
  InstanceType:
    Description: The instance type
    Type: String
    Default: t2.small
  KeyName:
    Description: The key pair name
    Type: AWS::EC2::KeyPair::KeyName
  TargetGroupARNs:
    Description: Target group for the instances
    Type: String
  VpcId:
    Description: The VPC ID
    Type: AWS::EC2::VPC::Id
Resources:
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'asg-sg'
      VpcId: !Ref VpcId
  InstanceSecurityGroupInFromALB:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      GroupId: !Ref InstanceSecurityGroup
      IpProtocol: tcp
      FromPort: 80
      ToPort: 80
      SourceSecurityGroupId: !ImportValue 'alb:security-group'
  InstanceSecurityGroupInFromBastion:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      GroupId: !Ref InstanceSecurityGroup
      IpProtocol: tcp
      FromPort: 22
      ToPort: 22
      SourceSecurityGroupId: !ImportValue 'bastion-SecurityGroup'
  LaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !Ref AmiId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -x
          mkdir /opt/deploy
          cd /opt/deploy
          curl -O https://bootstrap.pypa.io/get-pip.py
          python get-pip.py
          pip install --upgrade pip &> deploy.out
          pip install awscli --ignore-installed six &>> deploy.out
          easy_install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz &>> deploy.out
          export INSTANCEID=$(curl -s -m 60 http://169.254.169.254/latest/meta-data/instance-id) &>> deploy.out

          yum install –y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm -y
          yum install nginx -y
          systemctl start nginx
          
          export myIP=$(hostname -I | awk '{print $1}')
          echo '<h1 style="color: #5e9ca0;">Kevin Lawson</h1>' > /usr/share/nginx/html/index.html
          echo '<p><strong><span style="color: #008080;">A4A demonstration website</span></strong></p>' >> /usr/share/nginx/html/index.html
          echo '<p><strong><span style="color: #008080;">Pretty much the most boring website ever</span></strong></p>' >> /usr/share/nginx/html/index.html
          echo '<h2 style="color: #2e6c80;">&nbsp;</h2>' >> /usr/share/nginx/html/index.html
          echo '<p id="date"></p>' >> /usr/share/nginx/html/index.html
          echo '<script>' >> /usr/share/nginx/html/index.html
          echo 'document.getElementById("date").innerHTML = Date();' >> /usr/share/nginx/html/index.html
          echo '</script>' >> /usr/share/nginx/html/index.html
          
          # report success
          cfn-signal --region ${AWS::Region} --resource AutoScalingGroup --stack ${AWS::StackName}
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      HealthCheckGracePeriod: 720 # Set to the expected launch time
      HealthCheckType: ELB
      LaunchConfigurationName: !Ref LaunchConfiguration
      MaxSize: !Ref MaximumInstances
      MinSize: !Ref MinimumInstances
      TargetGroupARNs: 
        - !Ref TargetGroupARNs
      VPCZoneIdentifier: !Split
        - ','
        - !ImportValue vpc:public-subnet:ids
    CreationPolicy:
      ResourceSignal:
        Count: !Ref MinimumViableInstances
        Timeout: PT24M
    UpdatePolicy:
      AutoScalingScheduledAction:
        IgnoreUnmodifiedGroupSizeProperties: true
      AutoScalingRollingUpdate:
        MinInstancesInService: 1
        MaxBatchSize: 1
        WaitOnResourceSignals: true
        PauseTime: PT15M
      AutoScalingReplacingUpdate:
        WillReplace: false