AWSTemplateFormatVersion: 2010-09-09

Description: deploy SSH bastion

Parameters:
  EnvironmentName:
    Description: Identify environment as non-prod or production
    Type: String
    Default: non-prod
    AllowedValues:
        - 'non-prod'
        - 'prod'
  VpcId:
    Description: VPC ID
    Type: String
  AmiId:
    Description: Bastion AMI
    Type: AWS::EC2::Image::Id
  KeyName:
    Description: key pair for ssh access
    Type: AWS::EC2::KeyPair::KeyName
  InstanceType:
    Description: 'Instance type of the SSH bastion host/instance.'
    Type: String
    Default: 't2.nano'
  SubDomainName:
    Description: hostname for the DNS entry
    Type: String
    Default: 'ssh-bastion'
  PublicHostedZoneName:
    Description: DNS zone name with trailing period
    Type: String
    Default: klawson.info.
Conditions:
  HasKeyName: !Not [!Equals [!Ref KeyName, '']]
  HasZone: !Not [!Equals [!Ref PublicHostedZoneName, '']]
Resources:
  RecordSet:
    Condition: HasZone
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneName: !Ref PublicHostedZoneName
      Name: !Sub '${SubDomainName}.${PublicHostedZoneName}'
      ResourceRecords:
      - !Ref EIP
      TTL: 600
      Type: A

  SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: SSH to the bastion from the world
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: '0.0.0.0/0'
      VpcId: !Ref VpcId

  EIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref Bastion
      Domain: vpc

  Bastion:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref AmiId
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref SecurityGroup
      SubnetId: !Select [1, !Split [",", !ImportValue 'vpc:public-subnet:ids']]
      Tags:
        -
          Key: Name
          Value: ssh-bastion
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -ex
          mkdir /opt/deploy
          cd /opt/deploy
          curl -O https://bootstrap.pypa.io/get-pip.py
          python get-pip.py
          pip install --upgrade pip &> deploy.out
          pip install awscli --ignore-installed six &>> deploy.out
          easy_install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz &>> deploy.out
          export INSTANCEID=$(curl -s -m 60 http://169.254.169.254/latest/meta-data/instance-id) &>> deploy.out

Outputs:
  SecurityGroup:
    Description: 'Use this Security Group to reference incoming traffic from the SSH bastion host/instance.'
    Value: !Ref SecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-SecurityGroup'
  IPAddress:
    Description: 'The public IP address of the SSH bastion host/instance.'
    Value: !Ref EIP
    Export:
      Name: !Sub '${AWS::StackName}-IP'
